# Introduction to Python programming

In [1]:
# the line below is more Jupyter "magic" to enable inline plots...
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
!pip install pytext-nlp

## Importing Modules

* modules contain specialized functionality in Python
* "standard library" contains basic functions (e.g. math)
* external modules can be installed for more specialized functionality (e.g. linear algebra).

You can import an entire module, or import all functions from a module.

In [2]:
import math
x = math.cos(2 * math.pi)
print(x)

1.0


In [3]:
from math import *
x = cos(2 * pi)
print(x)

1.0


Importing modules can be inconvenient because it requires more typing, but importing everything can lead to "namespace collisions":

In [4]:
sin = "gluttony"
from math import sin
print(sin)

<built-in function sin>


Aliases and specific imports can alleviate these problems.

In [5]:
from math import cos, pi

x = cos(pi)
print(x)

-1.0


In [6]:
import math as m

x = m.cos(m.pi)
print(x)

-1.0


## Module documentation & information

Importing a module doesn't tell you how to use it! You can check the [standard library documentation](https://docs.python.org/3/library/index.html), or most modules have their own, but this isn't convenient.

* `dir` tells you the name of functions/variables in a module
* `help` prints the information about functions

In [64]:
import math

print(dir(math))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [8]:
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.7/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
    

Help doesn't always work! Functions must have a "docstring", and variables can provide unhelpful help.

In [9]:
help(pi)

Help on float object:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __int__(self, /)
 |      int(self)
 |  
 |  __le__

## Variables and types

### Protected names

There are a number of Python keywords that cannot be used as variable names. These keywords are:

    and, as, assert, break, class, continue, def, del, elif, else, except, 
    exec, finally, for, from, global, if, import, in, is, lambda, not, or,
    pass, print, raise, return, try, while, with, yield

Note: Be aware of the keyword `lambda`!

## Fundamental types

In [10]:
# integers
x = 1
type(x)

int

In [11]:
# float
x = 1.0
type(x)

float

In [12]:
# boolean
b1 = True
b2 = False

type(b1)

bool

In [13]:
# complex numbers: note the use of `j` to specify the imaginary part
x = 1.0 - 1.0j
type(x)

complex

## Compound types: Strings, List and dictionaries

### Strings

In [14]:
s = "Hello world"
type(s)

str

In [15]:
# length of the string: the number of characters
len(s)

11

In [16]:
# replace a substring in a string with something else
s2 = s.replace("world", "test")
print(s2)

Hello test


In [65]:
print(s[0])
print(s[0:5])
print(s[-3:])

H
Hello
rld


### String printing/formatting

In [18]:
print("str1", "str2", "str3")  # The print statement concatenates strings with a space

str1 str2 str3


In [19]:
print("str1", 1.0, False, -1j)  # The print statements converts all arguments to strings

str1 1.0 False (-0-1j)


In [20]:
print("str1" + "str2" + "str3") # strings added with + are concatenated without space

str1str2str3


In [21]:
# alternative, more intuitive way of formatting a string 
s3 = 'value1 = {1}, value2 = {0}'.format(3.1415, 1.5)

print(s3)

value1 = 1.5, value2 = 3.1415


### List

Lists are very similar to strings, except that each element can be of any type.

The syntax for creating lists in Python is `[...]`:

In [66]:
l = [1,2,3,4,5,6,7,8,9,10]

print(type(l))
print(l)
print(l[2:5])
print(l[1:8:2])

<class 'list'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[3, 4, 5]
[2, 4, 6, 8]


Elements in a list do not all have to be of the same type, and can be "nested"

In [23]:
l = [1, 'a', 1.0, 1-1j]

print(l)

[1, 'a', 1.0, (1-1j)]


In [67]:
nested_list = [1, [2, [3, [4, [5]]]]]

print(nested_list)
print(nested_list[1])
print(nested_list[1][1])

[1, [2, [3, [4, [5]]]]]
[2, [3, [4, [5]]]]
[3, [4, [5]]]


The `range` function is useful for generating lists, but it works using an "iterator":

In [68]:
start = 10
stop = 30
step = 2

r = range(start, stop, step)
print(r)
print(r[3])
print(type(r))
r = list(r)
print(r)

range(10, 30, 2)
16
<class 'range'>
[10, 12, 14, 16, 18, 20, 22, 24, 26, 28]


#### Adding, inserting, modifying, and removing elements from lists

In [26]:
# create a new empty list
l = []

# add an elements using `append`
l.append("A")
l.append("d")
l.append("d")

print(l)

['A', 'd', 'd']


We can modify lists by assigning new values to elements in the list. In technical jargon, lists are *mutable*.

In [27]:
l[1] = "p"
l[2] = "p"

print(l)

l[1:3] = ["d"]

print(l)

['A', 'p', 'p']
['A', 'd']


Insert an element at an specific index using `insert`

In [69]:
#l = []
l.insert(0, "i")
l.insert(1, "n")
l.insert(2, "s")
l.insert(3, "e")
l.insert(4, "r")
l.insert(5, "t")
l.insert(3,5)

print(l)

['i', 'n', 's', 5, 'e', 'r', 't', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Remove first element with specific value using 'remove'

In [70]:
l.remove(5)

print(l)

['i', 'n', 's', 'e', 'r', 't', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


### Tuples

Tuples are like lists, except that they cannot be modified once created, that is they are *immutable*. 

In Python, tuples are created using the syntax `(..., ..., ...)`, or even `..., ...`:

In [71]:
point = (10, 20)

print(point, type(point))

(10, 20) <class 'tuple'>


If we try to assign a new value to an element in a tuple we get an error:

In [72]:
point[0] = 20

TypeError: 'tuple' object does not support item assignment

Python functions with multiple outputs return tuples instead of lists - this can be confusing!

In [32]:
def two_numbers():
    return 10, 20

t = two_numbers()
print(t)
#t[0] = 5

(10, 20)


### Dictionaries

Dictionaries are also like lists, except that each element is a key-value pair. The syntax for dictionaries is `{key1 : value1, ...}`:

In [33]:
params = {"parameter1" : 1.0,
          "parameter2" : 2.0,
          "parameter3" : 3.0,}

print(type(params))
print(params)

<class 'dict'>
{'parameter1': 1.0, 'parameter2': 2.0, 'parameter3': 3.0}


Parameters can be re-assigned or added:

In [73]:
params["parameter1"] = "A"
params["parameter2"] = "B"

# add a new entry
params["parameter4"] = "D"

params[5] = {'subdict_key':5}

print(params)
print(params[5]['subdict_key'])

del params[5]
print(params)

{'parameter1': 'A', 'parameter2': 'B', 'parameter3': 3.0, 'parameter4': 'D', 5: {'subdict_key': 5}}
5
{'parameter1': 'A', 'parameter2': 'B', 'parameter3': 3.0, 'parameter4': 'D'}


You can iterate through dictionaries with the `keys`, `values`, and `items` functions:

In [74]:
for key in params:
    print(key)
    
print('_'*10)
    
for key,val in params.items():
    print(key, val)

parameter1
parameter2
parameter3
parameter4
__________
parameter1 A
parameter2 B
parameter3 3.0
parameter4 D


## Loops

### **`for` loops**:

In [36]:
for x in [1,2,3]:
    print(x)

1
2
3


In [37]:
scwp = ["scientific", "computing", "with", "python"]
for word in scwp:
    print(word)

scientific
computing
with
python


Sometimes it is useful to have access to the indices of the values when iterating over a list. We can use the `enumerate` function for this:

In [75]:
for idx, x in enumerate(scwp):
    print(idx, x)
    
# or

for id_x in enumerate(scwp):
    print(id_x)
    idx, x = id_x
    print(idx,x)

0 scientific
1 computing
2 with
3 python
(0, 'scientific')
0 scientific
(1, 'computing')
1 computing
(2, 'with')
2 with
(3, 'python')
3 python


### List comprehensions: Creating lists using `for` loops:

A convenient and compact way to initialize lists:

In [76]:
xx = [a**2 for a in range(0,5)]

print(xx)

x0 = [math.cos(xi) for xi in xx if xi==0]
print(x0)

[0, 1, 4, 9, 16]
[1.0]


## Functions

Function definitions use `def` and are based on indentation.

In [40]:
def func0():   
    print("test")

In [77]:
func0()
func0()

test
test


A "docstring" follows directly after the function definition, should describe the basic behavior, and is accessed via the `help` function.

In [42]:
def func1(s):
    """
    Print a string 's' and tell how many characters it has    
    """
    
    print(s + " has " + str(len(s)) + " characters")
    return 'something'

In [43]:
help(func1)

Help on function func1 in module __main__:

func1(s)
    Print a string 's' and tell how many characters it has



In [44]:
func1("test")


test has 4 characters


'something'

Functions return `None` by default. Functions that returns a value use the `return` keyword:

In [45]:
def square(x):
    """
    Return the square of x.
    """
    return x ** 2

In [46]:
xsquared = square(4)
print(xsquared)

16


### Default argument and keyword arguments

In a definition of a function, we can give default values to the arguments the function takes:

In [47]:
def myfunc(x, p=2, debug=False):
    if debug:
        print("evaluating myfunc for x = {} using exponent p = {}".format(x,p))
    return x**p

In [48]:
myfunc(5)
myfunc(5, debug=True)
myfunc(p=3, debug=True, x=7)

evaluating myfunc for x = 5 using exponent p = 2
evaluating myfunc for x = 7 using exponent p = 3


343

Python also uses a `*args` and `**kwargs` syntax to pass lists/dictionaries as arguments and keyword arguments. This is a more advanced topic, but you will sometimes see it.

In [49]:
kwargs = {'x':7, 'p':1, 'debug':False}
myfunc(**kwargs)

def multiargs(first,second,third):
    print(first, second, third)
    
#args = ['matlab', 'argument', 'passing sucks']
kwargs = {'first':'python', 'second':'argument', 'third':'passing rules'}
multiargs(**kwargs)


python argument passing rules


### Unnamed "anonymous" functions (lambda function)

These are like @ functions in Matlab, but are less useful in Python thanks to optional keyword arguments.

In [50]:
f1 = lambda x: x**2
    
# is equivalent to 

def f2(x):
    return x**2

print(f1(5))
print(f2(5))

25
25


## Classes

Classes are the key features of object-oriented programming. A class is a structure for representing an object and the operations that can be performed on the object. Classes contain:

* *attributes* (variables)
* *methods* (functions)

Classes have some special variables and conventions:

* `self` is the first argument to all methods. This object is a self-reference.
* Special methods are denoted by two underscores:

    * `__init__`: The name of the method that is invoked when the object is first created.
    * `__str__` : A method that is invoked when a simple string representation of the class is needed, as for example when printed.
    * There are many more, see http://docs.python.org/2/reference/datamodel.html#special-method-names

In [51]:
class Point:
    """
    Simple class for representing a point in a Cartesian coordinate system.
    """
    
    def __init__(self, x, y):
        """
        Create a new Point at x, y.
        """
        self.x = x
        self.y = y
        
    def translate(self, dx, dy):
        """
        Translate the point by dx and dy in the x and y direction.
        """
        self.x += dx
        self.y += dy
        
    def __str__(self):
        return("2D point at [%f, %f]" % (self.x, self.y))
    
a = Point
print(a)

<class '__main__.Point'>


After creating a class you can create "instances" of the class:

In [52]:
p1 = Point(0, 0) # this will invoke the __init__ method in the Point class

print(p1)         # this will invoke the __str__ method
print(p1.x)       # here we print the x attribute of p1

p2 = Point(0, 0) #this is a different instance of the "Point" class
print(p1 == p2) #these are different instances that simply happen to have the same attributes
# note that if you wanted this to be true you can modify the __eq__ method

p1.x = 5

p2.y = 1

print(p1)
print(p2)

2D point at [0.000000, 0.000000]
0
False
2D point at [5.000000, 0.000000]
2D point at [0.000000, 1.000000]


You can call "methods" in the following way:

In [53]:
p1.translate(0.25, 1.5) #note that we don't have to tell p1 where it is... it already "knows"!

print(p1)
print(p2)

2D point at [5.250000, 1.500000]
2D point at [0.000000, 1.000000]


### Inheritance

Classes can "inherit" behavior from other classes. This is very convenient, but also can be very confusing!

Inheritance should only be used by Python "experts", but you may encounter it in reading other's code.

In [54]:
class PointList(list): #This class "inherits" everything from list!
    """
    Simple class for representing a point in a Cartesian coordinate system which unneccesarily behaves like a list. 
    """
    
    def __init__(self, x, y):
        """
        Create a new Point at x, y.
        """
        list.__init__(self,[x,y]) #we can now initialize the point as a "list"
        self.x = self[0] = x #the "double equal" operator pins two variables together -- AVOID IT!
        self.y = self[1] = y
        
    def translate(self, dx, dy):
        """
        Translate the point by dx and dy in the x and y direction.
        """
        self.x += dx
        self.y += dy
        
    def append(self, z):
        print("This class only supports 2 dimensions!")
        return
pointlist = PointList(0,1)
print(dir(p1))
print(dir(pointlist))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'translate', 'x', 'y']
['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort', 'translate', 'x', 'y']


In [78]:
pl1 = PointList(1,1)
print(pl1)
pl1.append(3)
print(pl1)
pl1 = pl1 + [3] #inheritance can make things behave unexpectedly if not used wisely
print(pl1)

[1, 1]
This class only supports 2 dimensions!
[1, 1]
[1, 1, 3]


## Modules

Good code minimizes redundancy - if you are typing the same thing twice you are doing it wrong!

Modules allow you to easily re-use code. This enables:

* better readability
* easier maintanance (debugging/troubleshooting)
* easier to extend/share

In [79]:
%%file mymodule.py
"""
Example of a python module. Contains a variable called my_variable,
a function called my_function, and a class called MyClass.
"""

my_variable = 0

def my_function():
    """
    Example function
    """
    return my_variable
    
class MyClass:
    """
    Example class.
    """

    def __init__(self):
        self.variable = my_variable
        
    def set_variable(self, new_value):
        """
        Set self.variable to a new value
        """
        self.variable = new_value
        
    def get_variable(self):
        return self.variable

Overwriting mymodule.py


We can import the module `mymodule` into our Python program using `import`, and read the doc string with `help`:

In [57]:
import mymodule
help(mymodule)

Help on module mymodule:

NAME
    mymodule

DESCRIPTION
    Example of a python module. Contains a variable called my_variable,
    a function called my_function, and a class called MyClass.

CLASSES
    builtins.object
        MyClass
    
    class MyClass(builtins.object)
     |  Example class.
     |  
     |  Methods defined here:
     |  
     |  __init__(self)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |  
     |  get_variable(self)
     |  
     |  set_variable(self, new_value)
     |      Set self.variable to a new value
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)

FUNCTIONS
    my_function()
        Example function

DATA
    my_variable = 0

FILE
    /Users/jagritisahoo/Documents/co

We can now access the variables, functions, and classes in "mymodule"

In [80]:
print(mymodule.my_variable)
myvar = mymodule.my_function()
print(myvar)
my_class = mymodule.MyClass() 
my_class.set_variable(10)
print(my_class.get_variable())

0
0
10


## Exceptions

Exceptions allow you to create ("raise") and "handle" errors in Python. Another advanced topic, but one you should be aware of.

In [81]:
raise Exception("description of the error")

Exception: description of the error

In [82]:
raise KeyError("this built-in error deals with keys not found in a dictionary")

KeyError: 'this built-in error deals with keys not found in a dictionary'

Errors enable aborting a function if a condition occurs:

In [61]:
def myfunction(int_arg):
    if type(int_arg) is not int:
        raise TypeError("This function requires an integer.")
    return int_arg

In [62]:
myfunction('a')

TypeError: This function requires an integer.

You can "catch" errors with the try/except syntax, but be careful! Errors are often there for a reason!

In [63]:
try:
    myfunction(1)
    print(notdefined)
except TypeError: #best practice is to check for a specific error.
    print("Caught an exception")
print('Code still working...')

NameError: name 'notdefined' is not defined

## Further reading

* http://github.com/jrjohansson/scientific-python-lectures - Lecture 2 is the more detailed versions of this lecture.
* http://www.python.org - The official web page of the Python programming language.
* http://www.python.org/dev/peps/pep-0008 - Style guide for Python programming. Highly recommended. 
* http://www.greenteapress.com/thinkpython/ - A free book on Python programming.
* [Python Essential Reference](http://www.amazon.com/Python-Essential-Reference-4th-Edition/dp/0672329786) - A good reference book on Python programming.

# Numpy -  multidimensional data arrays

## Introduction

Numpy is not part of the "standard library", but it might as well be for engineers. Numpy is Python's answer to Matlab - the "back end" is implemented in C so its performance is very fast (comparable to Matlab).

In [1]:
!pip install numpy

In [2]:
import numpy as np

## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

In [41]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])

print(v)

# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2], [3, 4]])

print(M)

type(v), type(M)

[1 2 3 4]
[[1 2]
 [3 4]]


(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape and size of an array by using the `shape` and `size` properties.

In [42]:
print(v.shape)
print(M.shape)
print(v.size)
print(M.size)

(4,)
(2, 2)
4
4


Arrays are similar to lists, but they must contain a single type:

In [43]:
M[0,0] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [44]:
M = np.array([[1, 2], [3, 4]], dtype=complex)

M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

### Creating arrays with functions

It is often more efficient to generate large arrays instead of creating them from lists. There are a few useful functions for this in numpy:

* `np.arange` - create a range with a specified step size (endpoints not included)
* `np.linspace` - create a range with a specified number of points (endpoints *are* included)
* `np.logspace` - create a range with a specified number of points in log space (endpoints *are* included)
* `np.mgrid` - create points on a multi-dimensional grid (similar to meshgrid in matlab)
* `np.random.rand` - create random number matrix from a uniform distribution
* `np.random.randn` - create random number matrix from a standard normal distribution
* `np.zeros` - create a matrix of zeros
* `np.ones` - create a matrix of ones
* `np.eye` - create identity matrix

In [7]:
x = np.arange(0, 10, 0.5) # arguments: start, stop, step
print(x)
x = np.linspace(0,10,15)
print(x)
x = np.logspace(0,3,10,base=10)
print(x)
print([np.log10(xi) for xi in x])

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]
[   1.            2.15443469    4.64158883   10.           21.5443469
   46.41588834  100.          215.443469    464.15888336 1000.        ]
[0.0, 0.33333333333333337, 0.6666666666666666, 1.0, 1.3333333333333333, 1.6666666666666665, 2.0, 2.333333333333333, 2.6666666666666665, 3.0]


In [8]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
print(x)
print(y)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [9]:
# uniform random numbers in [0,1]
rand_uniform = np.random.rand(3,3)
print(rand_uniform)
# standard normal distributed random numbers
rand_normal = np.random.randn(3,3)
print(rand_normal)

[[0.48012987 0.47237413 0.69472084]
 [0.96773638 0.90948751 0.98234481]
 [0.04180248 0.35583907 0.86649923]]
[[ 0.74037594  0.44313288 -0.1305822 ]
 [-0.27459825 -0.6022369   0.80975182]
 [ 1.92298721  1.21303185  1.75858636]]


In [10]:
z = np.zeros((3,3)) #note that these take 1 tuple argument instead of multiple integers
one = np.ones((3,3))
I = np.eye(3,3) #but not this one... this is an annoying inconsistency.
print(z)
print(one)
print(I)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## File I/O

* Numpy has built-in functionality for reading/writing CSV or TSV (tab-separated value) files

Consider the following example:

In [45]:
!head stockholm_td_adj.dat

1800  1  1    -6.1    -6.1    -6.1 1
1800  1  2   -15.4   -15.4   -15.4 1
1800  1  3   -15.0   -15.0   -15.0 1
1800  1  4   -19.3   -19.3   -19.3 1
1800  1  5   -16.8   -16.8   -16.8 1
1800  1  6   -11.4   -11.4   -11.4 1
1800  1  7    -7.6    -7.6    -7.6 1
1800  1  8    -7.1    -7.1    -7.1 1
1800  1  9   -10.1   -10.1   -10.1 1
1800  1 10    -9.5    -9.5    -9.5 1


In [46]:
data = np.genfromtxt('stockholm_td_adj.dat')
print(data.shape)

(77431, 7)


Numpy can also write `csv` files from arrays:

In [13]:
M = np.random.rand(6,6)
np.savetxt("random-matrix.csv", M)
M1 = np.genfromtxt("random-matrix.csv")
print(M1==M)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


## Manipulating arrays

Once we generate `numpy` arrays, we need to interact with them. This involves a few operations:

* indexing - accessing certain elements
* index "slicing" - accessing certain subsets of elements
* fancy indexing - combinations of indexing and slicing

This is not very different from Matlab.

We can index elements in an array using square brackets and indices:

In [14]:
# v is a vector, and has only one dimension, taking one index
print(v[0])
# M is a matrix, or a 2 dimensional array, taking two indices 
print(M[1,1])
# If an index is ommitted then the whole row is returned
print(M[1])
# This means that we can also index with multiple brackets if we want to type more:
print(M[1][1] == M[1,1])

1
0.48592621526273416
[0.39320197 0.48592622 0.36324379 0.01187931 0.16797644 0.59601437]
True


The same thing can be achieved with using `:` instead of an index: 

In [15]:
print(M[1,:]) # row 1
print(M[:,1]) # column 1

[0.39320197 0.48592622 0.36324379 0.01187931 0.16797644 0.59601437]
[0.00146124 0.48592622 0.63602386 0.34178976 0.26215253 0.90135028]


We can assign new values to elements or rows in an array using indexing:

In [16]:
M[0,0] = 1
print(M)
M[:,2] = -1
print(M)

[[1.         0.00146124 0.65320253 0.53819379 0.85305548 0.15992202]
 [0.39320197 0.48592622 0.36324379 0.01187931 0.16797644 0.59601437]
 [0.12604362 0.63602386 0.87630864 0.81996614 0.84820733 0.83141949]
 [0.86420059 0.34178976 0.24237393 0.82042579 0.46236983 0.72346029]
 [0.15369664 0.26215253 0.290678   0.70923425 0.72081884 0.79705541]
 [0.41168725 0.90135028 0.8154973  0.22475208 0.32129672 0.36781922]]
[[ 1.          0.00146124 -1.          0.53819379  0.85305548  0.15992202]
 [ 0.39320197  0.48592622 -1.          0.01187931  0.16797644  0.59601437]
 [ 0.12604362  0.63602386 -1.          0.81996614  0.84820733  0.83141949]
 [ 0.86420059  0.34178976 -1.          0.82042579  0.46236983  0.72346029]
 [ 0.15369664  0.26215253 -1.          0.70923425  0.72081884  0.79705541]
 [ 0.41168725  0.90135028 -1.          0.22475208  0.32129672  0.36781922]]


### Index slicing

Index slicing is the name for the syntax `M[lower:upper:step]` to extract a subset of an array.

In [17]:
A = np.arange(1,20)
print(A)
print(A[1:8:2])
print(A[1:8]) #This is the most common usage
print(A[5:])
print(A[-3:])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[2 4 6 8]
[2 3 4 5 6 7 8]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[17 18 19]


Array values can also be assigned using slicing:

In [18]:
A[1:3] = [-2,-3]
print(A)

[ 1 -2 -3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Index slicing works exactly the same way for multidimensional arrays:

In [47]:
R = np.random.rand(10,10,10)
print(R.shape)
subR = R[3:5, 1:4, 0]
print(subR.shape)
print(subR)

(10, 10, 10)
(2, 3)
[[0.58999857 0.72976466 0.56025706]
 [0.03397562 0.33914918 0.33279598]]


### Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [20]:
R = np.random.rand(4,4)
print(R)
print('-'*10)
row_indices = [1, 3]
print(R[row_indices])

[[0.66063383 0.78185722 0.08538858 0.50967112]
 [0.96025493 0.9992953  0.81209343 0.64494647]
 [0.88079298 0.35600591 0.59912385 0.27916972]
 [0.0380985  0.52180105 0.84137092 0.99267959]]
----------
[[0.96025493 0.9992953  0.81209343 0.64494647]
 [0.0380985  0.52180105 0.84137092 0.99267959]]


In [21]:
col_indices = [1, -1] # remember, index -1 means the last element
print(R[row_indices, col_indices])

[0.9992953  0.99267959]


### Transposing arrays

Arrays can easily be transposed with `.T`.

In [22]:
skinny = np.random.rand(8,2)
print(skinny)
print(skinny.shape)
fat = skinny.T
print(fat)
print(fat.shape)

[[0.8828413  0.95798832]
 [0.63045611 0.16988725]
 [0.00438886 0.78269257]
 [0.55362746 0.00678702]
 [0.92757275 0.74391061]
 [0.26054478 0.94333052]
 [0.27704329 0.62743922]
 [0.59401807 0.54693468]]
(8, 2)
[[0.8828413  0.63045611 0.00438886 0.55362746 0.92757275 0.26054478
  0.27704329 0.59401807]
 [0.95798832 0.16988725 0.78269257 0.00678702 0.74391061 0.94333052
  0.62743922 0.54693468]]
(2, 8)


## Linear algebra in Numpy

Formulating your code as matrix-matrix and matrix-vector operations in Numpy will make it much more efficient. We will briefly cover syntax for:

* scalar*vector
* scalar*matrix
* matrix*vector
* matrix*matrix
* inverse
* determinant
* solve Ax=b

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [23]:
v1 = np.arange(0, 5)
print(v1)
print('-'*10)
print(v1*2)
print('-'*10)
print(v1+2)

[0 1 2 3 4]
----------
[0 2 4 6 8]
----------
[2 3 4 5 6]


Same goes for matrices:

In [24]:
M = np.random.rand(2,2)
print(M)
print('-'*10)
print(M*2)
print('-'*10)
print(M+2)

[[0.80135151 0.98493697]
 [0.87576621 0.15106052]]
----------
[[1.60270302 1.96987393]
 [1.75153243 0.30212105]]
----------
[[2.80135151 2.98493697]
 [2.87576621 2.15106052]]


### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations. This is different from Matlab!

In [25]:
v1 = np.arange(2,6)
print(v1)
print(v1*v1)
print(v1/v1)

print('-'*10)

M = np.array([[1,2],[3,4]])
print(M)
print(M*M)

[2 3 4 5]
[ 4  9 16 25]
[1. 1. 1. 1.]
----------
[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]


### Matrix algebra

What about matrix mutiplication?

* use the `dot` function (recommended)
* use the `matrix` class (`+`, `*`, `-` use matrix algebra)

In [48]:
A = np.eye(3,3)
v = np.array([1,2,3])
print(np.dot(A,v))
print(np.dot(A,A))
print(np.dot(v,v))

A = np.matrix(A)
v = np.matrix(v)
print(A*v.T)
print(A*A)
print(v*v.T)

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
14
[[1.]
 [2.]
 [3.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[14]]


### Common matrix operations

We can easily calculate the inverse and determinant using `inv` and `det`

In [27]:
A = np.array([[-1,2],[3,-1]])
print(A)
print(np.linalg.inv(A))
print(np.linalg.det(A))

[[-1  2]
 [ 3 -1]]
[[0.2 0.4]
 [0.6 0.2]]
-5.000000000000001


## Data processing in with Numpy arrays

Numpy provides a number of functions to calculate statistics of datasets in arrays. 

For example, let's calculate some properties from the Stockholm temperature dataset used above.

In [49]:
# reminder, the tempeature dataset is stored in the data variable:
print(data.shape)
print('Y: {}, M: {}, D: {}, Avg: {}, Low: {}, Hi: {}, Loc: {}'.format(*data[0, :]))

(77431, 7)
Y: 1800.0, M: 1.0, D: 1.0, Avg: -6.1, Low: -6.1, Hi: -6.1, Loc: 1.0


We can use numpy to easily calculate:

* mean
* standard deviation
* variance
* min/max

In [29]:
print(np.mean(data))
print(data.mean())
# the mean of the entire dataset is pretty meaningless...

# the temperature data is in column 3
print(data[:,3].mean())

278.0810699664401
278.0810699664401
6.197109684751585


In [30]:
#We can calculate standard deviation, variance, min, and max in the same way:
print('stdev:',np.std(data[:,3]))
print('variance:',np.var(data[:,3]))
print('min',np.min(data[:,3]))
print('max',np.max(data[:,3]))

#note that all of these are also *methods* of the array *class*
print(data[:,3].std())

stdev: 8.282271621340573
variance: 68.59602320966341
min -25.8
max 28.3
8.282271621340573


### Calculations with higher-dimensional data

Sometimes we want to apply an operation across a single dimension. For example, we might want the mean of very column. This is controlled with the `axis` argument:

In [50]:
avgs = np.mean(data,axis=0)
print(data.shape)
print(avgs.shape)
print(avgs)

(77431, 7)
(7,)
[1.90550041e+03 6.52304633e+00 1.57292945e+01 6.19710968e+00
 5.83217058e+00 5.78546190e+00 1.00000000e+00]


In [32]:
R = np.random.rand(3,3,3)
print(R.mean())
print(R.mean(axis=2))

0.5852023410024356
[[0.495667   0.53786811 0.62776447]
 [0.5308831  0.65776438 0.5564225 ]
 [0.67219267 0.55226669 0.63599215]]


In [33]:
print(R)

[[[0.20205199 0.43400518 0.85094382]
  [0.90902935 0.53537367 0.16920129]
  [0.86653719 0.18185072 0.8349055 ]]

 [[0.65254124 0.02925621 0.91085185]
  [0.53407727 0.9578823  0.48133358]
  [0.54450772 0.94190815 0.18285163]]

 [[0.68145727 0.80588745 0.52923329]
  [0.07569367 0.87914578 0.70196062]
  [0.11497311 0.95688812 0.83611522]]]


## Reshaping and resizing arrays

The shape of a Numpy array can be modified without copying the underlaying data, which makes it a fast operation even for large arrays. There are rules that govern how this reshaping takes place.

In [34]:
print(R.shape)
n,m,p = R.shape
Q = R.reshape((n, m*p))
print(Q.shape)
F = R.flatten() #the "flatten" function turns the whole array into a vector
print(F.shape)

(3, 3, 3)
(3, 9)
(27,)


Two common pitfalls in reshaping arrays:

* Reshaping rules do not behave as expected
* Reshaping provides a different "view" of the data, but **does not copy it**

In [35]:
print(R[0,0,0])
print(F[0])
print(R[0,1,0])
print(F[1])
print(F[3])

0.20205199044075084
0.20205199044075084
0.9090293527816719
0.4340051832902998
0.9090293527816719


In [36]:
print(R[0,0,0])
Q[0] = 10
print(R[0,0,0]) #resize does not copy the data
F[0] = 6
print(R[0,0,0]) #flatten makes copies

0.20205199044075084
10.0
10.0


### Making "deep copy"

If you really want a copy of an array, use the `np.copy` function:

In [37]:
A = np.array([[1, 2], [3, 4]])
print(A)
B = A
B[0,0] = 10
print(A)
Acopy = np.copy(A)
Acopy[1,1] = 6
print(A)

[[1 2]
 [3 4]]
[[10  2]
 [ 3  4]]
[[10  2]
 [ 3  4]]


## Using arrays in conditions

`if` statements and other boolean expressions are ambiguous with arrays.

* `any` checks to see if any members are true/false
* `all` checks to see if all members are true/false

In [51]:
print(M)
print(M>1)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
[[False  True]
 [ True  True]]


In [39]:
if (M > 1).any():
    print("at least one element in M is larger than 1")
else:
    print("no element in M is larger than 1")

at least one element in M is larger than 1


In [40]:
if (M > 1).all():
    print("all elements in M are larger than 1")
else:
    print("all elements in M are not larger than 1")

all elements in M are not larger than 1


In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
from IPython.display import Image

 # SciPy - Library of scientific algorithms for Python

The SciPy framework builds on top of the low-level NumPy framework for multidimensional arrays, and provides a large number of higher-level scientific algorithms. Today we will discuss a few that are most useful for data science:

* Integration ([scipy.integrate](http://docs.scipy.org/doc/scipy/reference/integrate.html))
* Optimization ([scipy.optimize](http://docs.scipy.org/doc/scipy/reference/optimize.html))
* Interpolation ([scipy.interpolate](http://docs.scipy.org/doc/scipy/reference/interpolate.html))
* Linear Algebra ([scipy.linalg](http://docs.scipy.org/doc/scipy/reference/linalg.html))
* Statistics ([scipy.stats](http://docs.scipy.org/doc/scipy/reference/stats.html))
* File IO ([scipy.io](http://docs.scipy.org/doc/scipy/reference/io.html))

In addition, you may wish to review Lecture 3 of Johanssen that covers others:

* Special Functions ([scipy.special](http://docs.scipy.org/doc/scipy/reference/special.html))
* Fourier Transforms ([scipy.fftpack](http://docs.scipy.org/doc/scipy/reference/fftpack.html))
* Signal Processing ([scipy.signal](http://docs.scipy.org/doc/scipy/reference/signal.html))
* Sparse Eigenvalue Problems ([scipy.sparse](http://docs.scipy.org/doc/scipy/reference/sparse.html))
* Multi-dimensional image processing ([scipy.ndimage](http://docs.scipy.org/doc/scipy/reference/ndimage.html))


We can import the entire `scipy` module, or specific functions:

In [ ]:
import scipy as sp
from scipy import linalg as la
import numpy as np #we almost always need numpy too

### Numerical integration: fixed data

You can use the trapezoidal rule or Simpson's rule to integrate (x,y) data:

In [ ]:
from scipy.integrate import trapz, simps

x = np.linspace(1,100,100)
x3 = x**3
x3_integral = ((100**4)/4) - (1/4)

x3_trapz = trapz(x3, x)
x3_simps = simps(x3,x)

print(x3_trapz)
print(x3_simps)
print(x3_integral)

### Numerical integration: quadrature

The quadrature function allows integration of the form:

$\displaystyle \int_a^b f(x) dx$

and is the most accurate form of integration if `f(x)` is known. Scipy can do single, double, or triple integrals with `quad`, `dblquad` and `tplquad`.

In [ ]:
from scipy.integrate import quad, dblquad, tplquad

def f(x):
    return x**3

In [ ]:
x_lower = 1 # the lower limit of x
x_upper = 100 # the upper limit of x

val, abserr = quad(f, x_lower, x_upper)

print("integral value = {}, absolute error = {}, real answer= {}".format(val,abserr,x3_integral))

Argument passing can be handled with optional arguments or use the `args` argument:

In [ ]:
def f(x, n=3):
    return x**n

args = (3,)
val, abserr = quad(f, x_lower, x_upper)

print(val, abserr)

Higher-dimensional integration works similarly, except that boundary "curves" have to be defined. This is a place where `lambda` functions are very useful.

In [ ]:
def integrand(x, y):
    return np.exp(-x**2-y**2)

x_lower = -np.inf  
x_upper = np.inf #infinity can be used as a limit
y_lower = 0
y_upper = 10

val, abserr = dblquad(integrand, x_lower, x_upper, lambda x: y_lower, lambda x: y_upper)

print(val, abserr)

## Interpolation

Interpolation is simple and convenient in scipy: The `interp1d` function, when given arrays describing X and Y data, returns and object that behaves like a function that can be called for an arbitrary value of x (in the range covered by X), and it returns the corresponding interpolated y value:

In [ ]:
from scipy.interpolate import interp1d
from scipy import randn

def f(x):
    return np.sin(x)

n = np.arange(0, 10)  
x = np.linspace(0, 9, 100)

y_meas = f(n) + 0.1 * randn(len(n)) # simulate measurement with noise
y_real = f(x)

fig, ax = plt.subplots(figsize=(10,4))
ax.plot(n, y_meas, 'bs', label='noisy data')
ax.plot(x, y_real, 'k', lw=2, label='true function')

In [ ]:
linear_interpolation = interp1d(n, y_meas, kind='linear')
y_interp1 = linear_interpolation(x)

cubic_interpolation = interp1d(n, y_meas, kind='cubic')
y_interp2 = cubic_interpolation(x)

fig, ax = plt.subplots(figsize=(10,4))
ax.plot(n, y_meas, 'bs', label='noisy data')
ax.plot(x, y_real, 'k', lw=2, label='true function')
ax.plot(x, y_interp1, 'r', label='linear interp')
ax.plot(x, y_interp2, 'g', label='cubic interp')
ax.legend(loc=3);

## Optimization

Optimization (finding minima or maxima of a function) is a large field in mathematics, and optimization of complicated functions or in many variables can be rather involved. Here we will only look at a few very simple cases. For a more detailed introduction to optimization with SciPy see: http://scipy-lectures.github.com/advanced/mathematical_optimization/index.html

### Finding a minima

Let's first look at how to find the minima of a simple function of a single variable:

In [ ]:
from scipy import optimize

def f(x):
    return 4*x**3 + (x-2)**2 + x**4

fig, ax  = plt.subplots()
x = np.linspace(-5, 3, 100)
ax.plot(x, f(x));

There are many types of optimizers available. We will use the common `BFGS` and `CG` optimizers here, but you can read more in the [documentation](https://docs.scipy.org/doc/scipy/reference/optimize.html).

In [ ]:
from scipy.optimize import minimize
x_min = minimize(f, 0.5, method='CG')
# method?
# output?
print(x_min)

### Solving an equation

* solve equations using root finding by expressing the equation as $f(x) = 0$ 
* use the `fsolve` function which requires an initial guess.

In [ ]:

def f(x):
    return np.sin(3*x)*(1/x)

In [ ]:
fig, ax  = plt.subplots(figsize=(10,4))
x = np.linspace(1, 10, 200)
y = f(x)
ax.plot(x, y)
ax.plot([0,11],[0,0],'k')

In [ ]:
optimize.fsolve(f, 3)

## Statistics

The `scipy.stats` module contains a large number of statistical distributions, statistical functions and tests. For a complete documentation of its features, see http://docs.scipy.org/doc/scipy/reference/stats.html.

In [ ]:
from scipy import stats

# create a (continous) random variable with normal distribution
Y = stats.norm()
print(Y)
type(Y)

In [ ]:
x = np.linspace(-5,5,100)

fig, axes = plt.subplots(3,1, sharex=True) #< we will get to this later...

# plot the probability distribution function (PDF)
axes[0].plot(x, Y.pdf(x))

# plot the commulative distributin function (CDF)
axes[1].plot(x, Y.cdf(x));

# plot histogram of 1000 random realizations of the stochastic variable Y
axes[2].hist(Y.rvs(size=1000), bins=50);

In [ ]:
# We can also create a Poisson distribution (this is used in modeling the frequency of random events)

X = stats.poisson(3) # poisson distribution with an expectation value of 4

n = np.arange(0,20)

fig, axes = plt.subplots(3,1, sharex=True)

# plot the probability mass function (PMF)
axes[0].step(n, X.pmf(n))

# plot the commulative distribution function (CDF)
axes[1].step(n, X.cdf(n))

# plot histogram of 1000 random realizations of the stochastic variable X
axes[2].hist(X.rvs(size=1000),bins=n);

We can easily calculate the statistics of these distributions:

In [ ]:
print(Y.mean(), Y.std(), Y.var()) # normal distribution

print(X.mean(), X.std(), X.var()) # poission distribution

### Statistical tests

We can use a t-test to test if two sets of (independent) random data have the same mean. The null hypothesis is that the two sets of data have the *same mean*:

In [ ]:
t_statistic, p_value = stats.ttest_ind(Y.rvs(size=1000)+3, X.rvs(size=1000),equal_var=False)
#note that this test assumes equal variance by default.

print("t-statistic =", t_statistic)
print("p-value =", p_value)

We can also use a 1-sample t-test to test if the mean of a single sample of data has mean 0.1 (the true mean is 0.0):

In [ ]:
t_statistic, p_value = stats.ttest_1samp(Y.rvs(size=1000), 0.1)
print("t-statistic =", t_statistic)
print("p-value =", p_value)

## Linear algebra

The linear algebra module of scipy contains more advanced matrix-related functions than numpy. Here we will look at:

* linear equation solving
* eigenvalue solvers

However, numerous other advanced features are available. The detailed documetation is available at: http://docs.scipy.org/doc/scipy/reference/linalg.html

### Linear equation systems

Linear equation systems on the matrix form

$A x = b$

where $A$ is a matrix and $x,b$ are vectors can be solved like:

In [ ]:
from scipy.linalg import solve

N = 3
A = np.random.rand(N,N)
b = np.random.rand(N)

x = solve(A, b)

print(x)
# check
np.dot(A, x) - b

We can also do the same with

$A X = B$

where $A, B, X$ are matrices:

In [ ]:
A = np.random.rand(N,N)
B = np.random.rand(N,N)

X = solve(A, B)
# check
np.dot(A, X) - B

### Eigenvalues and eigenvectors

The eigenvalue problem for a matrix $A$:

$\displaystyle A v_n = \lambda_n v_n$

where $v_n$ is the $n$th eigenvector and $\lambda_n$ is the $n$th eigenvalue.

To calculate eigenvalues of a matrix, use the `eigvals` and for calculating both eigenvalues and eigenvectors, use the function `eig`:

In [ ]:
from scipy.linalg import eigvals, eig
evals = eigvals(A)
print(evals)

evals, evecs = eig(A)
print(evals)
print(evecs)

$\displaystyle A v_n = \lambda_n v_n$

The eigenvectors corresponding to the $n$th eigenvalue (stored in `evals[n]`) is the $n$th *column* in `evecs`, i.e., `evecs[:,n]`. To verify this, let's try mutiplying eigenvectors with the matrix and compare to the product of the eigenvector and the eigenvalue:

In [ ]:
n = 2

np.dot(A, evecs[:,n]) - evals[n] * evecs[:,n]

# matplotlib - Plotting in Python

Matplotlib has advantages:

* Easy to get started (MATLAB-like interface)
* Support for LaTeX formatted labels and texts
* Output in many formats, including PNG, PDF, SVG, EPS, and PGF.
* Extensive gallery of examples with source code (https://matplotlib.org/gallery.html)
* Programmatic control over all aspects of figures

Programmatic control is a blessing and a curse...

Other plotting tools are available (Plotly, Bokeh, D3, ...) but `matplotlib` is the workhorse.

Matplotlib can be used in two ways:

* `pylab` modules (works like MATLAB)
* object-oreinted interface (harder but more powerful)

In [ ]:
%matplotlib inline

## MATLAB-like API

The easiest way to get started with plotting using matplotlib is often to use the MATLAB-like API provided by matplotlib. 

It is designed to be compatible with MATLAB's plotting functions, so it is easy to get started with if you are familiar with MATLAB.

To use this API from matplotlib, we need to include the symbols in the `pylab` module: 

In [ ]:
from pylab import *

x = np.linspace(0, 5, 10)
y = x ** 2

figure()
plot(x, y, 'r')
xlabel('x')
ylabel('y')
title('title')
show()

Most of the plotting related functions in MATLAB are covered by the `pylab` module. For example, subplot and color/symbol selection:

In [ ]:
subplot(1,2,1)
plot(x, y, 'r--')
subplot(1,2,2)
plot(y, x, 'g*-');

## The matplotlib object-oriented interface

The `pylab` interface is easy, but limited.

* Use simple global functions that match with MATLAB
* Objects are implicitly defined and hidden from users.

The `pyplot` object-oriented interface is harder to learn, but much more powerful.

* Use objects instead of global functions.
* Explicitly define objects - much better for multiple figures.

In [ ]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
fig = plt.figure()

axes = fig.add_axes([0.1, 0.1, 0.8, 0.8]) # left, bottom, width, height (range 0 to 1)

axes.plot(x, y, 'r')

axes.set_xlabel('x')
axes.set_ylabel('y')
axes.set_title('title');

In [ ]:
fig = plt.figure()

axes1 = fig.add_axes([0.1, 0.1, 0.8, 0.8]) # main axes
axes2 = fig.add_axes([0.2, 0.5, 0.4, 0.3]) # inset axes

# main figure
axes1.plot(x, y, 'r')
axes1.set_xlabel('x')
axes1.set_ylabel('y')
axes1.set_title('title')

# insert
axes2.plot(y, x, 'g')
axes2.set_xlabel('y')
axes2.set_ylabel('x')
axes2.set_title('insert title');

This gives us lots of control, but can also be inconvenient. There are tools to make life a little easier, like `subplots`:

In [ ]:
fig, axes = plt.subplots()

axes.plot(x, y, 'r')
axes.set_xlabel('x')
axes.set_ylabel('y')
axes.set_title('title');

In [ ]:
fig, axes = plt.subplots(nrows=1, ncols=2)

for ax in axes:
    ax.plot(x, y, 'r')
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_title('title')
    
#fig.tight_layout()

### Figure size, aspect ratio and DPI

Matplotlib allows control of:

* figure size (aspect ration)
* dpi (resolution)

when the figure is created. This also works with `subplots`. If you are planning to put the figure into a report/manuscript it is worthwhile to set this!

In [ ]:
fig = plt.figure(figsize=(8,4), dpi=100)

#OR 

fig, axes = plt.subplots(figsize=(8,4))

axes.plot(x, y, 'r')
axes.set_xlabel('x')
axes.set_ylabel('y')
axes.set_title('title')  

### Saving figures

To save a figure to a file we can use the `savefig` method in the `Figure` class. You can output in many formats, but the most common are:

* PNG (raster)
* JPG (raster)
* SVG (vector)
* PDF (vector)

The SVG and PDF formats are great because they can be edited afterward with vector graphics programs like Inkscape or Adobe Illustrator.

In [ ]:
# if saving rasterized images you can set the dpi (300 is standard)
fig.savefig("filename.png", dpi=300)

fig.savefig("filename.pdf")

### Titles, labels, and legends

You should always label axes (including units!), and legends are useful if you have many things plotted at once. You can also set the title of each axis. Note that these are controlled by the `axes` object, not the `Figure` object.

In [ ]:
axes.set_title("title")
axes.set_xlabel("x [units]")
axes.set_ylabel("y [units]")

fig

**Legends**

Legends for curves in a figure can be added in two ways.

* `legend` method of the axis object 
* `label` argument of plot

In [ ]:
axes.legend(["curve1"]);
fig

In [ ]:
axes.plot(x, x**2, label="curve1")
axes.plot(x, x**3, label="curve2")
axes.legend()

fig

In [ ]:
axes.legend(loc=0) # let matplotlib decide the optimal location
axes.legend(loc=1) # upper right corner
axes.legend(loc=2) # upper left corner
axes.legend(loc=3) # lower left corner
axes.legend(loc=4) # lower right corner
# .. many more options are available
fig

Putting it all together...

In [ ]:
fig, ax = plt.subplots()

ax.plot(x, x**2, label="y = x**2")
ax.plot(x, x**3, label="y = x**3")
ax.legend(loc=2); # upper left corner
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_title('title');

### Setting colors, linewidths, linetypes

When plotting a line the following keyword arguments control its properties:

* color (r, g, b, k, y, m, #000000,...)
* alpha (0 to 1 for transparancy) 
* marker ('o','+','^',...)
* linestyle or ls ('-', ':', '--', ...)
* linewidth or lw (1, 2, 3, 4 ...)

In [ ]:
fig, ax = plt.subplots()

ax.plot(x, x+1, color="red", alpha=0.5) # half-transparant red
ax.plot(x, x+2, color="#1155dd")        # RGB hex code for a bluish color
ax.plot(x, x+3, color="#15cc55")        # RGB hex code for a greenish color
ax.plot(x, x+4, color='b', marker='^', ls='--') #dashed blue line with triangle markers

There is also a Matlab-like syntax for simple plots:

In [ ]:
ax.plot(x, x+5, '-ok')        # black line with circle markers
fig

Lots more examples...

In [ ]:
fig, ax = plt.subplots(figsize=(12,6))

ax.plot(x, x+1, color="blue", linewidth=0.25)
ax.plot(x, x+2, color="blue", linewidth=0.50)
ax.plot(x, x+3, color="blue", linewidth=1.00)
ax.plot(x, x+4, color="blue", linewidth=2.00)

# possible linestype options ‘-‘, ‘--’, ‘-.’, ‘:’, ‘steps’
ax.plot(x, x+5, color="red", lw=2, linestyle='-')
ax.plot(x, x+6, color="red", lw=2, ls='-.')
ax.plot(x, x+7, color="red", lw=2, ls=':')

# possible marker symbols: marker = '+', 'o', '*', 's', ',', '.', '1', '2', '3', '4', ...
ax.plot(x, x+ 8, color="green", lw=2, ls='--', marker='+')
ax.plot(x, x+9, color="green", lw=2, ls='--', marker='o')
ax.plot(x, x+10, color="green", lw=2, ls='--', marker='s')
ax.plot(x, x+11, color="green", lw=2, ls='--', marker='1')

# marker size and color
ax.plot(x, x+12, color="purple", lw=1, ls='-', marker='o', markersize=2)
ax.plot(x, x+13, color="purple", lw=1, ls='-', marker='o', markersize=4)
ax.plot(x, x+14, color="purple", lw=1, ls='-', marker='o', markersize=8, markerfacecolor="red")
ax.plot(x, x+15, color="purple", lw=1, ls='-', marker='s', markersize=8, 
        markerfacecolor="yellow", markeredgewidth=2, markeredgecolor="blue");

### Control over axis appearance

There are many options for modifying axis appearance. The most basic one is controlling the range of the plot. You can use:

* `set_xlim` - control x range
* `set_ylim` - control y range
* `axis('tight')` - automaticlly "tighten" the axis range.

You can also control tick positions, tick labels, log scale, etc. See the many examples online.

In [ ]:
fig, axes = plt.subplots(1, 3, figsize=(12, 4))

axes[0].plot(x, x**2, x, x**3)
axes[0].set_title("default axes ranges")

axes[1].plot(x, x**2, x, x**3)
axes[1].axis('tight')
axes[1].set_title("tight axes")

axes[2].plot(x, x**2, x, x**3)
axes[2].set_ylim([0, 0.4])
axes[2].set_xlim([0.25, 0.6])
axes[2].set_title("custom axes range");

### Twin axes

Sometimes it is useful to have dual x or y axes in a figure; for example, when plotting curves with different units together. Matplotlib supports this with the `twinx` and `twiny` functions:

In [ ]:
fig, ax1 = plt.subplots()

ax1.plot(x, x**2, lw=2, color="blue")
ax1.set_ylabel(r"area $(m^2)$", fontsize=18, color="blue") #note support for LaTeX-style formatting
for label in ax1.get_yticklabels(): #an example of controlling tick label color
    label.set_color("blue")
    
ax2 = ax1.twinx()
ax2.plot(x, x**3, lw=2, color="red")
ax2.set_ylabel(r"volume $(m^3)$", fontsize=18, color="red")
for label in ax2.get_yticklabels():
    label.set_color("red")

### Text annotation

Often it is useful to place annotations on a plot. There are two options:

* `text` - place text at an absolute position
* `annotate` - place text at a position relative to another point

`annotate` is useful if you want to draw arrows.

In [ ]:
fig, ax = plt.subplots()

t = np.arange(0.0, 5.0, 0.01)
s = np.cos(2*np.pi*t)
ax.plot(t, s, lw=2)

ax.text(s='this is a sin curve', x=0, y=1.3)

ax.annotate('local max', xy=(2, 1), xytext=(3, 1.5),
            arrowprops=dict(facecolor='black', shrink=0.05),
            )

#ax.set_ylim(-2,2)

### Colormap and contour figures

Colormaps and contour figures are useful for plotting functions of two variables. In most of these functions we will use a colormap to encode one dimension of the data. There are a number of predefined colormaps. It is relatively straightforward to define custom colormaps. For a list of pre-defined colormaps, see: http://www.scipy.org/Cookbook/Matplotlib/Show_colormaps

Plotting 3D data can be done with: 

* pcolor (show directly with x, y)
* contour (contour lines with x, y)
* imshow (interpolate and transpose)

See this [discussion](https://matplotlib.org/users/colormaps.html) of choosing color maps. The "perceptually uniform" color maps are preferred since they work with greyscale and are easier for colorblind people.

In [ ]:
#cook up some 3D data to plot

alpha = 0.7
phi_ext = 2 * np.pi * 0.5

def flux_qubit_potential(phi_m, phi_p):
    return 2 + alpha - 2 * np.cos(phi_p) * np.cos(phi_m) - alpha * np.cos(phi_ext - 2*phi_p)

phi_m = np.linspace(0, 2*np.pi, 100)
phi_p = np.linspace(0, 2*np.pi, 100)
X,Y = np.meshgrid(phi_p, phi_m)
Z = flux_qubit_potential(X, Y).T

In [ ]:
from matplotlib.cm import jet, RdBu, gray, viridis, plasma

fig, ax = plt.subplots()

p = ax.pcolor(X, Y, Z, cmap=viridis)#, vmin=abs(Z).min(), vmax=abs(Z).max())
cb = fig.colorbar(p, ax=ax)

In [ ]:
fig, ax = plt.subplots()

cnt = ax.contour(X, Y, Z, cmap=viridis)#, vmin=abs(Z).min(), vmax=abs(Z).max())
cb = fig.colorbar(cnt, ax=ax)

In [ ]:
fig, ax = plt.subplots()

im = ax.imshow(Z, cmap=viridis, vmin=abs(Z).min(), vmax=abs(Z).max(), extent=[0, 2, 0, 1])
im.set_interpolation('bilinear')

cb = fig.colorbar(im, ax=ax)

### Images

Matplotlib treats images as numpy arrays, which makes them easy to analyze. There is a toolkit designed specifically for images (`matplotlib.image`)

In [ ]:
import matplotlib.image as mpimg

img = mpimg.imread('bug.jpg') #we can read png or jpg
#print(img)
fig,ax = plt.subplots()
ax.imshow(img)

Images are 3D arrays with x,y,RGB

In [ ]:
print(img.shape)
ax.imshow(img[:,:,1],cmap=gray)
fig

It is easy to look at histograms:

In [ ]:
fig, axes = plt.subplots(1,2)
axes[0].imshow(img)
axes[0].set_title('image')

axes[1].hist(img[:,:,0].ravel(), bins=256)
axes[1].set_title('color histogram')

#How can we look at the greyscale histogram?

#fig.tight_layout()

## 3D figures

Matplotlib can make 3D plots, but its not easy. I recommend searching the [gallery](https://matplotlib.org/examples/mplot3d/) for examples if you really think you need a 3D plot.

In [ ]:
from mpl_toolkits.mplot3d import axes3d
import matplotlib.pyplot as plt
from matplotlib import cm

fig = plt.figure()
ax = fig.gca(projection='3d')
X, Y, Z = axes3d.get_test_data(0.05)
ax.plot_surface(X, Y, Z, rstride=8, cstride=8, alpha=0.3)
cset = ax.contourf(X, Y, Z, zdir='z', offset=-100, cmap=viridis)
cset = ax.contourf(X, Y, Z, zdir='x', offset=-40, cmap=viridis)
cset = ax.contourf(X, Y, Z, zdir='y', offset=40, cmap=viridis)

ax.set_xlabel('X')
ax.set_xlim(-40, 40)
ax.set_ylabel('Y')
ax.set_ylim(-40, 40)
ax.set_zlabel('Z')
ax.set_zlim(-100, 100)

plt.show()

## Further reading

* http://github.com/jrjohansson/scientific-python-lectures - Lecture 3 is the more detailed version of this lecture.
* http://numpy.scipy.org
* http://scipy.org/Tentative_NumPy_Tutorial
* http://scipy.org/NumPy_for_Matlab_Users - A Numpy guide for MATLAB users.

Lectures 3+4 of Johanssen: [http://github.com/jrjohansson/scientific-python-lectures](http://github.com/jrjohansson/scientific-python-lectures)

Scipy:
* http://www.scipy.org - The official web page for the SciPy project.
* http://docs.scipy.org/doc/scipy/reference/tutorial/index.html - A tutorial on how to get started using SciPy. 
* https://github.com/scipy/scipy/ - The SciPy source code. 

Matplotlib:
* http://www.matplotlib.org - The project web page for matplotlib.
* https://github.com/matplotlib/matplotlib - The source code for matplotlib.
* http://matplotlib.org/gallery.html - A large gallery showcaseing various types of plots matplotlib can create. Highly recommended! 
* http://www.loria.fr/~rougier/teaching/matplotlib - A good matplotlib tutorial.
* http://scipy-lectures.github.io/matplotlib/matplotlib.html - Another good matplotlib reference.

## Versions

In [ ]:
%reload_ext version_information
%version_information numpy, scipy, matplotlib